-- AlterTable
ALTER TABLE "User" ALTER COLUMN "credits" SET DEFAULT 0;

ALTER TABLE "User" ADD COLUMN "usedCredits" Int4 NOT NULL DEFAULT 0; 
ALTER TABLE "User" ADD COLUMN "grade" Int4 NOT NULL DEFAULT 0;
